SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 1;
START TRANSACTION;
SET time_zone = "+00:00";
SET innodb_lock_wait_timeout=43200;
SET GLOBAL innodb_lock_wait_timeout=43200;
SET GLOBAL max_allowed_packet=268435456;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `pfinfo` (
  `bandwidth` text NOT NULL,
  `updatetime` text NOT NULL,
  `addtime` text NOT NULL,
  `id` bigint(20) NOT NULL,
  `serviceid` text NOT NULL,
  `ptype` text NOT NULL,
  `rsip` text NOT NULL,
  `rport` text NOT NULL,
  `sport` text NOT NULL,
  `maxconnnum` text NOT NULL,
  `connnum` text NOT NULL,
  `status` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `pfinfo`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `pfinfo`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
